version: "3.8"

services:
  app:
    image: blog
    container_name: blog-container
    build:
      context: .
    volumes:
      - ./server/prisma:/backend/prisma
      - ./server/uploads:/backend/uploads
    ports:
      - "7007:7007"
    deploy:
      resources:
        limits:
          memory: 250M
    restart: on-failure
